# Generated by Django 4.1.1 on 2022-09-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_management', '0002_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='material_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_code', models.CharField(default='', max_length=50)),
                ('mat_desc', models.CharField(default='', max_length=50)),
                ('curr_stock', models.CharField(default='', max_length=50)),
                ('Uom', models.CharField(default='', max_length=50)),
                ('note1', models.CharField(default='', max_length=50)),
                ('note2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_code', models.CharField(default='', max_length=50)),
                ('vendor_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='material',
        ),
        migrations.AddField(
            model_name='material_master',
            name='note1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='material_master',
            name='note2',
            field=models.CharField(default='', max_length=50),
        ),
    ]
