# Generated by Django 4.1.1 on 2022-09-07 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms_management', '0003_material_stock_vendor_master_delete_material_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material_master',
            old_name='MatCode',
            new_name='matcode',
        ),
        migrations.RenameField(
            model_name='material_master',
            old_name='MatDesc',
            new_name='matdesc',
        ),
    ]
