# Generated by Django 4.1.1 on 2022-09-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_management', '0004_rename_matcode_material_master_matcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inbound_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRnum', models.CharField(default='', max_length=50)),
                ('matcode', models.CharField(default='', max_length=50)),
                ('matdesc', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('uom', models.CharField(default='', max_length=50)),
                ('scan_date', models.CharField(default='', max_length=50)),
                ('scan_time', models.CharField(default='', max_length=50)),
                ('vendor', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='outbound_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delnum', models.CharField(default='', max_length=50)),
                ('matcode', models.CharField(default='', max_length=50)),
                ('matdesc', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('uom', models.CharField(default='', max_length=50)),
                ('scan_date', models.CharField(default='', max_length=50)),
                ('scan_time', models.CharField(default='', max_length=50)),
                ('customer', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
