# Generated by Django 4.1.1 on 2022-09-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_management', '0007_rename_vendor_inbound_data_serial_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='inbound_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRnum', models.CharField(default='', max_length=50)),
                ('vendor', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('no_of_item', models.CharField(default='', max_length=50)),
                ('note1', models.CharField(default='', max_length=50)),
                ('note2', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='outbound_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delnum', models.CharField(default='', max_length=50)),
                ('customer', models.CharField(default='', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('no_of_item', models.CharField(default='', max_length=50)),
                ('note1', models.CharField(default='', max_length=50)),
                ('note2', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
